// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using Windows.ApplicationModel;
using Windows.Storage;

namespace Richasy.ReaderKernel.Toolkits.WinUI;

/// <summary>
/// 内核文本文件工具箱.
/// </summary>
public sealed partial class KernelTxtToolkit
{
    private const string MIME_TYPE = "application/epub+zip";

    private static readonly string CHAPTER_DIVISION_REGEX = string.Empty;
    private static readonly string[] CHAPTER_EXTRA_KEYS = ["序 ", "前言", "后记", "後記", "楔子", "附录", "附錄", "外傳", "外传", "番外"];

    /// <summary>
    /// 章节标题字符数限制.
    /// </summary>
    private static readonly int MAX_CHAPTER_TITLE_LENGTH = 50;

    /// <summary>
    /// 根目录地址.
    /// </summary>
    public static string RootPath { get; set; } = ApplicationData.Current.LocalFolder.Path;

    /// <summary>
    /// 根目录地址.
    /// </summary>
    public static string PackagePath { get; set; } = Package.Current.InstalledPath;

    private static string TXT_FOLDER_PATH => RootPath + "\\.txt-temp\\";

    private static string GENERATE_FOLDER_PATH => RootPath + "\\.epub-generate\\";

    private static string TEMP_FOLDER_PATH => RootPath + "\\.epub-temp\\";

    private static string TEMP_CSS_FOLDER_PATH => TEMP_FOLDER_PATH + "css\\";

    private static string TEMP_CSS_FILE_PATH => TEMP_CSS_FOLDER_PATH + "main.css";

    private static string TEMP_META_FOLDER_PATH => TEMP_FOLDER_PATH + "META-INF\\";

    private static string TEMP_CONTAINER_FILE_PATH => TEMP_META_FOLDER_PATH + "container.xml";

    private static string TEMP_MIME_TYPE_FILE_PATH => TEMP_FOLDER_PATH + "mimetype";

    private static string TEMP_CONTENT_OPF_PATH => TEMP_FOLDER_PATH + "content.opf";

    private static string TEMP_TOC_NCX_PATH => TEMP_FOLDER_PATH + "toc.ncx";

    private static string ASSETS_FOLDER_PATH => PackagePath + "\\Assets\\EpubAssets\\";

    private static string ASSETS_CSS_FILE_PATH => ASSETS_FOLDER_PATH + "css\\main.css";

    private static string ASSETS_META_FOLDER_PATH => ASSETS_FOLDER_PATH + "META-INF\\";

    private static string ASSETS_OPS_FOLDER_PATH => ASSETS_FOLDER_PATH + "OPS\\";

    private static string ASSETS_CONTAINER_FILE_PATH => ASSETS_META_FOLDER_PATH + "container.xml";

    private static string ASSETS_OPF_FILE_PATH => ASSETS_OPS_FOLDER_PATH + "content.opf";

    private static string ASSETS_NCX_FILE_PATH => ASSETS_OPS_FOLDER_PATH + "toc.ncx";

    private static string ASSETS_PAGE_PATH => ASSETS_FOLDER_PATH + "page.html";

    private static string ASSETS_TITLE_PAGE_PATH => ASSETS_FOLDER_PATH + "title-page.html";
}
