// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using System;
using System.Collections.Generic;

namespace Richasy.ReaderKernel.Connectors.Rss.Models.Feedbin;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
internal sealed class FeedbinTagging
{
    public int id { get; set; }
    public int feed_id { get; set; }
    public string name { get; set; }
}


internal sealed class FeedbinSubscription
{
    public int id { get; set; }
    public DateTimeOffset created_at { get; set; }
    public int feed_id { get; set; }
    public string title { get; set; }
    public string feed_url { get; set; }
    public string site_url { get; set; }
}

internal sealed class FeedbinEntity
{
    public long id { get; set; }
    public int feed_id { get; set; }
    public string title { get; set; }
    public string author { get; set; }
    public string summary { get; set; }
    public string content { get; set; }
    public string url { get; set; }
    public string extracted_content_url { get; set; }
    public DateTimeOffset published { get; set; }
    public DateTimeOffset created_at { get; set; }
}

internal sealed class FeedbinUpdateGroupRequest
{
    public string old_name { get; set; }

    public string new_name { get; set; }
}

internal sealed class FeedbinMarkReadRequest
{
    public List<long> updated_entries { get; set; }

}

internal sealed class FeedbinAddFeedRequest
{
    public string feed_url { get; set; }
}

#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
