// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using System.Collections.Generic;

namespace Richasy.ReaderKernel.Connectors.Rss.Models.GoogleReader;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
internal sealed class GoogleReaderAuthResponse
{
    public string SID { get; set; }
    public string LSID { get; set; }
    public string Auth { get; set; }
}

internal sealed class GoogleReaderSubscriptionResponse
{
    public List<Subscription> subscriptions { get; set; }
}

internal sealed class Subscription
{
    public string id { get; set; }
    public string title { get; set; }
    public List<Category> categories { get; set; }
    public string url { get; set; }
    public string htmlUrl { get; set; }
    public string iconUrl { get; set; }
    public string sortid { get; set; }
}

internal sealed class Category
{
    public string id { get; set; }
    public string label { get; set; }
}


internal sealed class GoogleReaderStreamContentResponse
{
    public string id { get; set; }
    public long updated { get; set; }
    public List<ArticleItem> items { get; set; }
    public string continuation { get; set; }
}

internal sealed class ArticleItem
{
    public string id { get; set; }
    public string crawlTimeMsec { get; set; }
    public string timestampUsec { get; set; }
    public long published { get; set; }
    public string title { get; set; }
    public List<Canonical> canonical { get; set; }
    public List<Alternate> alternate { get; set; }
    public List<string> categories { get; set; }
    public Origin origin { get; set; }
    public SummaryOrContent summary { get; set; }
    public SummaryOrContent content { get; set; }
    public string author { get; set; }
}

internal sealed class Origin
{
    public string streamId { get; set; }
    public string htmlUrl { get; set; }
    public string title { get; set; }
}

internal sealed class SummaryOrContent
{
    public string content { get; set; }
}

internal sealed class Canonical
{
    public string href { get; set; }
}

internal sealed class Alternate
{
    public string href { get; set; }
}

#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
