// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using System.Collections.Generic;

namespace Richasy.ReaderKernel.Connectors.Rss.Models.Inoreader;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释

internal sealed class InoreaderFolderListResponse
{
    public List<Folder> tags { get; set; }
}

internal sealed class InoreaderPreferenceResponse
{
    public Dictionary<string, List<Preference>> streamprefs { get; set; }
}

internal sealed class Folder
{
    public string id { get; set; }
    public string sortid { get; set; }
    public string type { get; set; }
    public int unread_count { get; set; }
    public int unseen_count { get; set; }
}

internal sealed class Preference
{
    public string id { get; set; }
    public string value { get; set; }
}

internal sealed class InoreaderAuthResult
{
    public string access_token { get; set; }

    public string refresh_token { get; set; }

    public long expires_in { get; set; }
}

#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
