// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using System;
using System.Collections.Generic;

namespace Richasy.ReaderKernel.Connectors.Rss.Models.Miniflux;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
internal sealed class MinifluxEntriesResponse
{
    public int total { get; set; }
    public Entry[] entries { get; set; }
}

internal sealed class MinifluxFeedCreateResponse
{
    public int feed_id { get; set; }
}

internal sealed class Entry
{
    public long id { get; set; }
    public int user_id { get; set; }
    public int feed_id { get; set; }
    public string status { get; set; }
    public string hash { get; set; }
    public string title { get; set; }
    public string url { get; set; }
    public string comments_url { get; set; }
    public DateTimeOffset published_at { get; set; }
    public DateTimeOffset created_at { get; set; }
    public DateTimeOffset changed_at { get; set; }
    public string content { get; set; }
    public string author { get; set; }
    public string share_code { get; set; }
    public bool starred { get; set; }
    public int reading_time { get; set; }
    public object enclosures { get; set; }
    public MinifluxFeed feed { get; set; }
    public List<string> tags { get; set; }
}

internal sealed class MinifluxFeed
{
    public int id { get; set; }
    public int user_id { get; set; }
    public string feed_url { get; set; }
    public string site_url { get; set; }
    public string title { get; set; }
    public DateTimeOffset checked_at { get; set; }
    public DateTimeOffset next_check_at { get; set; }
    public string etag_header { get; set; }
    public string last_modified_header { get; set; }
    public string parsing_error_message { get; set; }
    public int parsing_error_count { get; set; }
    public string scraper_rules { get; set; }
    public string rewrite_rules { get; set; }
    public bool crawler { get; set; }
    public string blocklist_rules { get; set; }
    public string keeplist_rules { get; set; }
    public string urlrewrite_rules { get; set; }
    public string user_agent { get; set; }
    public string cookie { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public bool disabled { get; set; }
    public bool no_media_player { get; set; }
    public bool ignore_http_cache { get; set; }
    public bool allow_self_signed_certificates { get; set; }
    public bool fetch_via_proxy { get; set; }
    public MinifluxCategory category { get; set; }
    public bool hide_globally { get; set; }
    public string apprise_service_urls { get; set; }
}

internal sealed class MinifluxCategory
{
    public int id { get; set; }
    public string title { get; set; }
    public int user_id { get; set; }
    public bool hide_globally { get; set; }
}

internal sealed class MinifluxAddFeedRequest
{
    public string feed_url { get; set; }

    public int category_id { get; set; }
}

internal sealed class MinifluxAddGroupRequest
{
    public string title { get; set; }
}

internal sealed class MinifluxMarkReadRequest
{
    public List<int> entry_ids { get; set; }

    public string status { get; set; }
}

internal sealed class MinifluxUpdateFeedRequest
{
    public int category_id { get; set; }

    public string title { get; set; }
}

internal sealed class MinifluxUpdateGroupRequest
{
    public string title { get; set; }
}
#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
