// Copyright (c) Reader Copilot. All rights reserved.
// <auto-generated />

using System.Collections.Generic;

namespace Richasy.ReaderKernel.Connectors.Rss.Models.NewsBlur;

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
internal sealed class NewsBlurFeedResponse
{
    public List<NewsBlurStory> stories { get; set; }
}

internal sealed class NewsBlurFeedListResponse
{
    public Dictionary<string, NewsBlurFeed> feeds { get; set; }
}

internal sealed class NewsBlurFeed
{
    public int id { get; set; }
    public string feed_title { get; set; }
    public string feed_address { get; set; }
    public string feed_link { get; set; }
    public int num_subscribers { get; set; }
    public string updated { get; set; }
    public int updated_seconds_ago { get; set; }
    public int fs_size_bytes { get; set; }
    public int archive_count { get; set; }
    public string last_story_date { get; set; }
    public int last_story_seconds_ago { get; set; }
    public int stories_last_month { get; set; }
    public int average_stories_per_month { get; set; }
    public int min_to_decay { get; set; }
    public int subs { get; set; }
    public bool is_push { get; set; }
    public bool is_newsletter { get; set; }
    public bool fetched_once { get; set; }
    public object search_indexed { get; set; }
    public bool not_yet_fetched { get; set; }
    public string favicon_color { get; set; }
    public string favicon_fade { get; set; }
    public string favicon_border { get; set; }
    public string favicon_text_color { get; set; }
    public bool favicon_fetching { get; set; }
    public string favicon_url { get; set; }
    public bool s3_page { get; set; }
    public bool s3_icon { get; set; }
    public bool disabled_page { get; set; }
    public int ps { get; set; }
    public int nt { get; set; }
    public int ng { get; set; }
    public bool active { get; set; }
    public int feed_opens { get; set; }
    public bool subscribed { get; set; }
}


internal sealed class NewsBlurStory
{
    public string story_hash { get; set; }
    public string story_date { get; set; }
    public string story_timestamp { get; set; }
    public string story_authors { get; set; }
    public string story_title { get; set; }
    public string story_content { get; set; }
    public string story_permalink { get; set; }
    public string[] image_urls { get; set; }
    public int story_feed_id { get; set; }
    public bool has_modifications { get; set; }
    public string guid_hash { get; set; }
    public string id { get; set; }
    public int reply_count { get; set; }
    public string short_parsed_date { get; set; }
    public string long_parsed_date { get; set; }
    public int read_status { get; set; }
    public int score { get; set; }
}

internal sealed class NewsBlurAuthResult
{
    public bool authenticated { get; set; }
}

#pragma warning restore CS1591 // 缺少对公共可见类型或成员的 XML 注释
