// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

#pragma warning disable SA1300, SA1516, SA1600, CS8618

namespace Richasy.RodelReader.Components.BookScraper.Internal.Responses.Pixiv;

internal sealed class PixivSearchResponse
{
    public bool error { get; set; }
    public PixivSearchResponseBody body { get; set; }
}

internal sealed class PixivSearchResponseBody
{
    public PixivSearchNovelResponse novel { get; set; }
}

internal sealed class PixivSearchNovelResponse
{
    public PixivSearchNovelItem[] data { get; set; }
    public int total { get; set; }
    public int lastPage { get; set; }
}

internal sealed class PixivSearchNovelItem
{
    public string id { get; set; }
    public string title { get; set; }
    public PixivCover cover { get; set; }
    public string[] tags { get; set; }
    public string userId { get; set; }
    public string userName { get; set; }
    public int bookmarkCount { get; set; }
    public string caption { get; set; }
    public DateTimeOffset latestPublishDateTime { get; set; }
}

internal sealed class PixivCover
{
    public PixivCoverUrls urls { get; set; }
}

internal sealed class PixivCoverUrls
{
    public string original { get; set; }
}
