// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

#nullable enable

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
#pragma warning disable SA1300 // Element should begin with upper-case letter
#pragma warning disable SA1516 // Elements should be separated by blank line
#pragma warning disable SA1600 // Elements should be documented

namespace Richasy.RodelReader.Sources.ApplePodcast.Models.Internal;

/// <summary>
/// iTunes 搜索/查询 API 响应.
/// </summary>
internal sealed class ITunesSearchResponse
{
    public int resultCount { get; set; }
    public List<ITunesResult>? results { get; set; }
}

internal sealed class ITunesResult
{
    public string? wrapperType { get; set; }
    public string? kind { get; set; }
    public long collectionId { get; set; }
    public long trackId { get; set; }
    public string? artistName { get; set; }
    public string? collectionName { get; set; }
    public string? trackName { get; set; }
    public string? feedUrl { get; set; }
    public string? trackViewUrl { get; set; }
    public string? artworkUrl30 { get; set; }
    public string? artworkUrl60 { get; set; }
    public string? artworkUrl100 { get; set; }
    public string? artworkUrl600 { get; set; }
    public DateTimeOffset releaseDate { get; set; }
    public int trackCount { get; set; }
    public string? country { get; set; }
    public string? primaryGenreName { get; set; }
    public string? contentAdvisoryRating { get; set; }
    public List<string>? genreIds { get; set; }
    public List<string>? genres { get; set; }
}

#pragma warning restore SA1600
#pragma warning restore SA1516
#pragma warning restore SA1300
#pragma warning restore CS1591
