// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

#nullable enable

#pragma warning disable CS1591 // 缺少对公共可见类型或成员的 XML 注释
#pragma warning disable SA1300 // Element should begin with upper-case letter
#pragma warning disable SA1516 // Elements should be separated by blank line
#pragma warning disable SA1600 // Elements should be documented

namespace Richasy.RodelReader.Sources.ApplePodcast.Models.Internal;

/// <summary>
/// iTunes 热门播客 API 响应.
/// </summary>
internal sealed class ITunesCategoryResponse
{
    public ITunesFeed? feed { get; set; }
}

internal sealed class ITunesFeed
{
    public List<ITunesFeedEntry>? entry { get; set; }
}

internal sealed class ITunesFeedEntry
{
    [JsonPropertyName("im:name")]
    public ITunesLabel? ImName { get; set; }

    [JsonPropertyName("im:image")]
    public List<ITunesImage>? ImImage { get; set; }

    [JsonPropertyName("summary")]
    public ITunesLabel? Summary { get; set; }

    [JsonPropertyName("id")]
    public ITunesId? Id { get; set; }

    [JsonPropertyName("im:artist")]
    public ITunesLabel? ImArtist { get; set; }
}

internal sealed class ITunesLabel
{
    [JsonPropertyName("label")]
    public string? Label { get; set; }
}

internal sealed class ITunesImage
{
    [JsonPropertyName("label")]
    public string? Label { get; set; }

    [JsonPropertyName("attributes")]
    public ITunesImageAttributes? Attributes { get; set; }
}

internal sealed class ITunesImageAttributes
{
    [JsonPropertyName("height")]
    public string? Height { get; set; }
}

internal sealed class ITunesId
{
    [JsonPropertyName("label")]
    public string? Label { get; set; }

    [JsonPropertyName("attributes")]
    public ITunesIdAttributes? Attributes { get; set; }
}

internal sealed class ITunesIdAttributes
{
    [JsonPropertyName("im:id")]
    public string? ImId { get; set; }
}

#pragma warning restore SA1600
#pragma warning restore SA1516
#pragma warning restore SA1300
#pragma warning restore CS1591
