// Copyright (c) Richasy. All rights reserved.
// <auto-generated />

#pragma warning disable SA1300, SA1516, SA1600, CS8618

namespace Richasy.RodelReader.Components.BookScraper.Internal.Responses.Google;

internal sealed class GoogleSearchResponse
{
    public string kind { get; set; }
    public int totalItems { get; set; }
    public GoogleBookItem[] items { get; set; }
}

internal sealed class GoogleBookItem
{
    public string kind { get; set; }
    public string id { get; set; }
    public string etag { get; set; }
    public string selfLink { get; set; }
    public GoogleVolumeInfo volumeInfo { get; set; }
    public GoogleSearchInfo searchInfo { get; set; }
}

internal sealed class GoogleVolumeInfo
{
    public string title { get; set; }
    public string[] authors { get; set; }
    public string publisher { get; set; }
    public string publishedDate { get; set; }
    public string description { get; set; }
    public GoogleIndustryIdentifier[] industryIdentifiers { get; set; }
    public int pageCount { get; set; }
    public string[] categories { get; set; }
    public GoogleImageLinks imageLinks { get; set; }
    public string language { get; set; }
    public string previewLink { get; set; }
    public string infoLink { get; set; }
    public string subtitle { get; set; }
}

internal sealed class GoogleImageLinks
{
    public string smallThumbnail { get; set; }
    public string thumbnail { get; set; }
}

internal sealed class GoogleIndustryIdentifier
{
    public string type { get; set; }
    public string identifier { get; set; }
}

internal sealed class GoogleSearchInfo
{
    public string textSnippet { get; set; }
}
